### ISSUE TITLE
Installation failed with existent cert-manager on EKS

### ISSUE THREAD

**Issue by riosje** [zilliztech/milvus-operator#108]
Hi, I've installed the operator following this instructions, for environments with existent cert-manager(v1.14.4) implementation
https://github.com/zilliztech/milvus-operator/blob/main/docs/installation/installation.md#installation
```shell
helm install milvus-operator \
  -n milvus-operator --create-namespace \
  https://github.com/zilliztech/milvus-operator/releases/download/v0.9.13/milvus-operator-0.9.13.tgz \
  --set checker.disableCertManagerCheck=true
```

## Issue
The pods are stuck on `ContainerCreating`
![image](https://github.com/zilliztech/milvus-operator/assets/55195249/d7cc9823-8896-40c4-b926-de8b7701c440)

```log
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    5m49s                 default-scheduler  Successfully assigned milvus-operator/milvus-operator-6c88644565-klhpn to ip-10-30-4-20.us-west-2.compute.internal
  Warning  FailedMount  98s (x10 over 5m48s)  kubelet            MountVolume.SetUp failed for volume "cert" : secret "milvus-operator-webhook-cert" not found
```

**ERROR**
`MountVolume.SetUp failed for volume "cert" : secret "milvus-operator-webhook-cert" not found`

Should I create another resource, what part am I missing?

Thank you so much for your help.

**Comment by riosje** [comment]
As far as I can see, it is trying to mount a secret with a cert, but there is not such secret.
does the helm chart should create that resource? or should I create it?

**Comment by haorenfsa** [comment]
@riosje The secret should be created by cert-manager in regular procedure. I doubt if the cert-manager is working correctly.

It seems very close to this issue https://github.com/milvus-io/milvus/issues/21961.

If you still can't solve it please provide me the logs of cert-manager.

**Comment by nustiueudinastea** [comment]
@haorenfsa  To me it seems that currently the operator chart is broken. If you look in the deployment.yaml of the chart, it depends on the webhook-cert secret and tries to mount it as a volume: https://github.com/zilliztech/milvus-operator/blob/bd4dc2b1c10065dcd13d880b6774ee30ba58fcec/charts/milvus-operator/templates/deployment.yaml#L66

Problem is, the issuer and the certificate resources are not create by the chart. Instead there is a code in the operator, that tries to create it if it does not exist: https://github.com/zilliztech/milvus-operator/blob/bd4dc2b1c10065dcd13d880b6774ee30ba58fcec/pkg/provisioner/cert_manager.go#L116

Problem is, that code never gets executed because the operator pod never starts. So there is a circular dependency there.

I hope I am overlooking something but as far as I can tell the chart can't work as is.

**Comment by haorenfsa** [comment]
related to https://github.com/zilliztech/milvus-operator/issues/132
